export {
  FILING_FACT_COMPARISON_SCHEMA_VERSION,
  FILING_FACT_COMPARISON_CLAIM,
  FILING_FACT_COMPARISON_FACT_KEYS,
  FILING_FACT_COMPARISON_DECLARED_VALIDATOR_BINDINGS,
  FILING_FACT_COMPARISON_CHECKS,
  FILING_FACT_COMPARISON_NOT_PROVEN,
  FILING_FACT_COMPARISON_LIMITS,
  FILING_FACT_COMPARISON_QUARANTINE_CODES,
  compareSyntheticFilingFactValidatorReports,
  type FilingFactComparisonDeclaredValidatorRole,
  type FilingFactComparisonDeclaredValidatorBinding,
  type FilingFactComparisonReceiptValidatorBinding,
  type FilingFactComparisonAudit,
  type FilingFactComparisonQuarantineCode,
  type FilingFactComparisonAgreementReceipt,
  type FilingFactComparisonQuarantinedResult,
  type FilingFactComparisonResult,
} from "./filing-fact-comparison";
